export const ADD_POST = 'ADD_POST';
export const POST_LOADING = 'POST_LOADING';
export const POST_FAILED = 'POST_FAILED';
export const POST_RESET = 'POST_RESET';

export const ADD_POST_IMAGES = 'ADD_POST_IMAGES';
export const POST_IMAGES_LOADING = 'POST_IMAGES_LOADING';
export const POST_IMAGES_FAILED = 'POST_IMAGES_FAILED';
export const POST_IMAGES_RESET = 'POST_IMAGES_RESET';

export const ADD_MYPOSTS = 'ADD_MYPOSTS';
export const MYPOSTS_LOADING = 'MYPOSTS_LOADING';
export const MYPOSTS_FAILED = 'MYPOSTS_FAILED';

export const ADD_POST_LIST = 'ADD_POST_LIST';
export const POST_LIST_LOADING = 'POST_LIST_LOADING';
export const POST_LIST_FAILED = 'POST_LIST_FAILED';
export const RESET_POST_LIST = 'RESET_POST_LIST';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGIN_RESET = 'LOGIN_RESET';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_FAILURE = 'PASSWORD_RESET_FAILURE';

export const SEND_PASSWORD_RESET_REQUEST = 'SEND_PASSWORD_RESET_REQUEST';
export const SEND_PASSWORD_RESET_SUCCESS = 'SEND_PASSWORD_RESET_SUCCESS';
export const SEND_PASSWORD_RESET_FAILURE = 'SEND_PASSWORD_RESET_FAILURE';

//Chat Rooms
export const ADD_ROOMS = 'ADD_ROOMS';
export const ROOMS_LOADING = 'ROOMS_LOADING';
export const ROOMS_FAILED = 'ROOMS_FAILED';
export const RESET_ROOMS = 'RESET_ROOMS';

export const ROOM_CREATION_SUCCESS = 'ROOM_CREATION_SUCCESS';
export const ROOM_CREATION_LOADING= 'ROOM_CREATION_LOADING';
export const ROOM_CREATION_FAILED = 'ROOM_CREATION_FAILED';

export const ADD_MESSAGES = 'ADD_MESSAGES';
export const MESSAGES_LOADING = 'MESSAGES_LOADING';
export const MESSAGES_FAILED = 'MESSAGES_FAILED';
export const RESET_MESSAGES = 'RESET_MESSAGES';

// Curret User
export const ADD_USER = 'ADD_USER';
export const USER_LOADING = 'USER_LOADING';
export const USER_FAILED = 'USER_FAILED';

export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_LOADING = 'DELETE_USER_LOADING';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';

export const ADD_USER_EMPLOYMENT = 'ADD_USER_EMPLOYMENT';
export const USER_EMPLOYMENT_LOADING = 'USER_EMPLOYMENT_LOADING';
export const USER_EMPLOYMENT_FAILED = 'USER_EMPLOYMENT_FAILED';

export const ADD_USER_EDUCATION = 'ADD_USER_EDUCATION';
export const USER_EDUCATION_LOADING = 'USER_EDUCATION_LOADING';
export const USER_EDUCATION_FAILED = 'USER_EDUCATION_FAILED';

export const ADD_USER_SKILLS = 'ADD_USER_SKILLS';
export const USER_SKILLS_LOADING = 'USER_SKILLS_LOADING';
export const USER_SKILLS_FAILED = 'USER_SKILLS_FAILED';

export const ADD_USER_CONTACT = 'ADD_USER_CONTACT';
export const USER_CONTACT_LOADING = 'USER_CONTACT_LOADING';
export const USER_CONTACT_FAILED = 'USER_CONTACT_FAILED';

export const ADD_USER_LANGUAGES = 'ADD_USER_LANGUAGES';
export const USER_LANGUAGES_LOADING = 'USER_LANGUAGES_LOADING';
export const USER_LANGUAGES_FAILED = 'USER_LANGUAGES_FAILED';

export const ADD_USER_PROFILE = 'ADD_USER_PROFILE';
export const USER_PROFILE_LOADING = 'USER_PROFILE_LOADING';
export const USER_PROFILE_FAILED = 'USER_PROFILE_FAILED';

export const ADD_USER_LIST = 'ADD_USER_LIST'
export const USER_LIST_LOADING = 'USER_LIST_LOADING'
export const USER_LIST_FAILED = 'USER_LIST_FAILED'

export const ADD_ANSWER_LIST = 'ADD_ANSWER_LIST';
export const ANSWER_LIST_LOADING = 'ANSWER_LIST_LOADING';
export const ANSWER_LIST_FAILED = 'ANSWER_LIST_FAILED';
export const RESET_ANSWER_LIST = 'RESET_ANSWER_LIST';

export const ADD_ANSWER_VOTE_LIST = 'ADD_ANSWER_VOTE_LIST';
export const ANSWER_VOTE_LIST_LOADING = 'ANSWER_VOTE_LIST_LOADING';
export const ANSWER_VOTE_LIST_FAILED = 'ANSWER_VOTE_LIST_FAILED';
export const RESET_ANSWER_VOTE_LIST = 'RESET_ANSWER_VOTE_LIST';

export const ADD_POST_VOTE_LIST = 'ADD_POST_VOTE_LIST';
export const POST_VOTE_LIST_LOADING = 'POST_VOTE_LIST_LOADING';
export const POST_VOTE_LIST_FAILED = 'POST_VOTE_LIST_FAILED';
export const RESET_POST_VOTE_LIST = 'RESET_POST_VOTE_LIST';

export const ADD_ANSWER_COMMENT_VOTE_LIST = 'ADD_ANSWER_COMMENT_VOTE_LIST';
export const ANSWER_COMMENT_VOTE_LIST_LOADING = 'ANSWER_COMMENT_VOTE_LIST_LOADING';
export const ANSWER_COMMENT_VOTE_LIST_FAILED = 'ANSWER_COMMENT_VOTE_LIST_FAILED';
export const RESET_ANSWER_COMMENT_VOTE_LIST = 'RESET_ANSWER_COMMENT_VOTE_LIST';

export const ADD_POST_COMMENT_VOTE_LIST = 'ADD_POST_COMMENT_VOTE_LIST';
export const POST_COMMENT_VOTE_LIST_LOADING = 'POST_COMMENT_VOTE_LIST_LOADING';
export const POST_COMMENT_VOTE_LIST_FAILED = 'POST_COMMENT_VOTE_LIST_FAILED';
export const RESET_POST_COMMENT_VOTE_LIST = 'RESET_POST_COMMENT_VOTE_LIST';

export const ADD_NOTIFICATIONS_LIST = 'ADD_NOTIFICATIONS_LIST';
export const NOTIFICATIONS_LIST_LOADING = 'NOTIFICATIONS_LIST_LOADING';
export const NOTIFICATIONS_LIST_FAILED = 'NOTIFICATIONS_LIST_FAILED';
export const RESET_NOTIFICATIONS_LIST = 'RESET_NOTIFICATIONS_LIST';

export const ADD_UNREAD_NOTIFICATIONS_LIST = 'ADD_UNREAD_NOTIFICATIONS_LIST';
export const UNREAD_NOTIFICATIONS_LIST_LOADING = 'UNREAD_NOTIFICATIONS_LIST_LOADING';
export const UNREAD_NOTIFICATIONS_LIST_FAILED = 'UNREAD_NOTIFICATIONS_LIST_FAILED';
export const RESET_UNREAD_NOTIFICATIONS_LIST = 'RESET_UNREAD_NOTIFICATIONS_LIST';

export const ADD_POST_COMMENTS = 'ADD_POST_COMMENTS';
export const POST_COMMENTS_LOADING = 'POST_COMMENTS_LOADING';
export const POST_COMMENTS_FAILED = 'POST_COMMENTS_FAILED';

export const ADD_ANSWER_COMMENTS = 'ADD_ANSWER_COMMENTS';
export const ANSWER_COMMENTS_LOADING = 'ANSWER_COMMENTS_LOADING';
export const ANSWER_COMMENTS_FAILED = 'ANSWER_COMMENTS_FAILED';

export const ADD_EVENTS = 'ADD_EVENTS';
export const EVENTS_LOADING = 'EVENTS_LOADING';
export const EVENTS_FAILED = 'EVENTS_FAILED';

export const ADD_WEBINARS = 'ADD_WEBINARS';
export const WEBINARS_LOADING = 'WEBINARS_LOADING';
export const WEBINARS_FAILED = 'WEBINARS_FAILED';

export const ADD_TOP_POSTS = 'ADD_TOP_POSTS';
export const TOP_POSTS_LOADING = 'TOP_POSTS_LOADING';
export const TOP_POSTS_FAILED = 'TOP_POSTS_FAILED';

//Profile Panels
export const ADD_LIKED_POSTS = 'ADD_LIKED_POSTS';
export const LIKED_POSTS_LOADING = 'LIKED_POSTS_LOADING';
export const LIKED_POSTS_FAILED = 'LIKED_POSTS_FAILED';

export const ADD_MYANSWERS = 'ADD_MYANSWERS';
export const MYANSWERS_LOADING = 'MYANSWERS_LOADING';
export const MYANSWERS_FAILED = 'MYANSWERS_FAILED';

//Firebase
export const FIREBASE_LOGIN_REQUEST = 'FIREBASE_LOGIN_REQUEST';
export const FIREBASE_LOGIN_SUCCESS = 'FIREBASE_LOGIN_SUCCESS';
export const FIREBASE_LOGIN_FAILURE = 'FIREBASE_LOGIN_FAILURE';

export const FIREBASE_LOGOUT_REQUEST = 'FIREBASE_LOGOUT_REQUEST';
export const FIREBASE_LOGOUT_SUCCESS = 'FIREBASE_LOGOUT_SUCCESS';
export const FIREBASE_LOGOUT_FAILURE = 'FIREBASE_LOGOUT_FAILURE';