export const ADD_POST = 'ADD_POST';
export const POST_LOADING = 'POST_LOADING';
export const POST_FAILED = 'POST_FAILED';

export const ADD_MYPOSTS = 'ADD_MYPOSTS';
export const MYPOSTS_LOADING = 'MYPOSTS_LOADING';
export const MYPOSTS_FAILED = 'MYPOSTS_FAILED';

export const ADD_POST_LIST = 'ADD_POST_LIST';
export const POST_LIST_LOADING = 'POST_LIST_LOADING';
export const POST_LIST_FAILED = 'POST_LIST_FAILED';
export const RESET_POST_LIST = 'RESET_POST_LIST';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGIN_RESET = 'LOGIN_RESET';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// Curret User
export const ADD_USER = 'ADD_USER';
export const USER_LOADING = 'USER_LOADING';
export const USER_FAILED = 'USER_FAILED';

export const ADD_USER_EMPLOYMENT = 'ADD_USER_EMPLOYMENT';
export const USER_EMPLOYMENT_LOADING = 'USER_EMPLOYMENT_LOADING';
export const USER_EMPLOYMENT_FAILED = 'USER_EMPLOYMENT_FAILED';

export const ADD_USER_PROFILE = 'ADD_USER_PROFILE';
export const USER_PROFILE_LOADING = 'USER_PROFILE_LOADING';
export const USER_PROFILE_FAILED = 'USER_PROFILE_FAILED';

export const ADD_ANSWER_LIST = 'ADD_ANSWER_LIST';
export const ANSWER_LIST_LOADING = 'ANSWER_LIST_LOADING';
export const ANSWER_LIST_FAILED = 'ANSWER_LIST_FAILED';
export const RESET_ANSWER_LIST = 'RESET_ANSWER_LIST';

export const ADD_ANSWER_VOTE_LIST = 'ADD_ANSWER_VOTE_LIST';
export const ANSWER_VOTE_LIST_LOADING = 'ANSWER_VOTE_LIST_LOADING';
export const ANSWER_VOTE_LIST_FAILED = 'ANSWER_VOTE_LIST_FAILED';
export const RESET_ANSWER_VOTE_LIST = 'RESET_ANSWER_VOTE_LIST';

export const ADD_POST_VOTE_LIST = 'ADD_POST_VOTE_LIST';
export const POST_VOTE_LIST_LOADING = 'POST_VOTE_LIST_LOADING';
export const POST_VOTE_LIST_FAILED = 'POST_VOTE_LIST_FAILED';
export const RESET_POST_VOTE_LIST = 'RESET_POST_VOTE_LIST';

export const ADD_NOTIFICATIONS_LIST = 'ADD_NOTIFICATIONS_LIST';
export const NOTIFICATIONS_LIST_LOADING = 'NOTIFICATIONS_LIST_LOADING';
export const NOTIFICATIONS_LIST_FAILED = 'NOTIFICATIONS_LIST_FAILED';
export const RESET_NOTIFICATIONS_LIST = 'RESET_NOTIFICATIONS_LIST';